"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { CitizenHeader } from "@/components/citizen-header";

type Detail = { data: { citizen: { name: string } }; property: { id: string; address: string; locality: string | null; area: string | null; status: string }; application?: { application_id: string; status: string }; events: Array<{ event_type: string; message: string; created_at: string }>; documents: Array<{ display_name: string; status: string }> };
const readableStatus = (status: string) => status.replaceAll("_", " ");
const eventMessage = (event: Detail["events"][number]) => ({ APPLICATION_SUBMITTED: "Property application submitted.", PROPERTY_VISIT_SCHEDULED: "Property visit scheduled.", PROPERTY_LOCATION_CHECKED: "Property location checked.", OWNER_PRESENCE_CONFIRMED: "Owner presence confirmed.", DOCUMENTS_CHECKED: "Ownership documents checked.", DOCUMENTS_REVIEWED: "Submitted documents reviewed.", OWNERSHIP_VERIFIED: "Ownership details confirmed.", FIELD_VERIFICATION_COMPLETED: "Field verification completed.", GOVERNMENT_REVIEW: "Verification record reviewed.", GOVERNMENT_APPROVED: "Government approval completed.", GOVERNMENT_APPROVAL_COMPLETED: "Government approval completed.", PASSPORT_ISSUED: "Property Passport issued." }[event.event_type] ?? "Verification update recorded.");

export default function PropertyDetail() {
  const { propertyId } = useParams<{ propertyId: string }>(); const [data, setData] = useState<Detail>(); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/upis/me").then(async (me) => { if (!me.ok) throw Error(); const response = await fetch(`/api/upis/properties/${propertyId}`); if (response.status === 404) { setError("Property not found."); return; } if (!response.ok) throw Error(); setData(await response.json() as Detail); }).catch(() => setError("Please sign in to view this property.")); }, [propertyId]);
  if (error) return <main className="min-h-screen bg-cream"><CitizenHeader/><p className="p-10">{error}</p></main>;
  if (!data) return <main className="min-h-screen bg-cream"><CitizenHeader/><p className="p-10">Loading property…</p></main>;
  const verified = data.property.status === "verified";
  return <main className="min-h-screen bg-cream"><CitizenHeader/><section className="mx-auto max-w-5xl px-5 pb-16 pt-8 sm:px-8"><Link href="/passport" className="text-sm font-semibold text-moss">← My properties</Link><div className="mt-7 rounded-[2rem] bg-[#315e4c] p-7 text-white sm:p-10"><p className="text-xs font-bold tracking-[.18em] text-[#c8ddc5]">PROPERTY · {data.property.id}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{data.property.address}</h1><p className="mt-2 text-lg text-[#c8ddc5]">{data.property.locality}</p><span className={`mt-6 inline-flex rounded-full px-3 py-2 text-xs font-bold ${verified ? "bg-[#e2f0df] text-moss" : "bg-[#fff0d9] text-[#7b542c]"}`}>{verified ? "VERIFIED IN THIS PROTOTYPE" : "VERIFICATION IN PROGRESS"}</span></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><Info label="OWNER" value={data.data.citizen.name}/><Info label="LOCATION" value={[data.property.address, data.property.locality].filter(Boolean).join(", ")}/><Info label="PROPERTY DETAILS" value={data.property.area || "Area recorded with application"}/><Info label="VERIFICATION" value={verified ? "Verified property" : "In review"}/><Info label="APPLICATION" value={data.application?.application_id ?? "Application being prepared"}/><Info label="DOCUMENTS" value={`${data.documents.length} protected ${data.documents.length === 1 ? "record" : "records"}`}/></div><div className="mt-8 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-[1.75rem] bg-white p-6 shadow-card"><p className="text-xs font-bold tracking-[.15em] text-saffron">DOCUMENTS</p><h2 className="mt-2 text-2xl font-semibold">Protected property records</h2><div className="mt-5 space-y-3">{data.documents.map((item) => <p key={item.display_name} className="flex items-center justify-between gap-3 rounded-xl bg-[#eef5ed] px-4 py-3 font-medium text-moss"><span>{item.display_name}</span><span className="text-xs font-bold">{readableStatus(item.status)}</span></p>)}</div><Link href={`/passport/property/${data.property.id}/vault`} className="mt-6 inline-flex rounded-2xl bg-moss px-5 py-3 text-sm font-semibold text-white">Open Property Vault</Link></section><section className="rounded-[1.75rem] border border-[#dbe4da] bg-white p-6"><p className="text-xs font-bold tracking-[.15em] text-saffron">VERIFICATION HISTORY</p><div className="mt-6">{data.events.map((event,index)=><div key={`${event.event_type}-${index}`} className="flex gap-4 pb-6 last:pb-0"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-moss text-xs text-white">✓</span><div><p className="text-xs font-bold tracking-[.1em] text-[#728076]">{new Date(event.created_at).toLocaleDateString()}</p><p className="mt-1 font-medium">{eventMessage(event)}</p></div></div>)}</div></section></div></section></main>;
}

function Info({ label, value }: { label: string; value: string }) { return <section className="rounded-[1.5rem] border border-[#dbe4da] bg-white p-5"><p className="text-xs font-bold tracking-[.14em] text-saffron">{label}</p><p className="mt-2 font-semibold text-ink">{value}</p></section>; }
