"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { VoiceButton } from "@/components/voice-button";
import { interpretRequest, NavigationResult } from "@/lib/navigator-service";

type Message = { role: "assistant" | "user"; text: string };
const prompts = ["I bought a property", "I already own property", "Check my application", "View my documents", "I lost my Passport", "I need help"];

export function AiNavigator() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "You don’t need to know the technical terms. Just tell us what you’re trying to do." }]);
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);
  const [result, setResult] = useState<NavigationResult | null>(null);
  const [awaitingSaleDeed, setAwaitingSaleDeed] = useState(false);
  const [toolStatus, setToolStatus] = useState<string | null>(null);
  const applyFallback = (text: string, history: Message[], serviceError = false) => { const next = interpretRequest(text, awaitingSaleDeed); setResult(next); setAwaitingSaleDeed(next.followUp === "saleDeed"); setMessages([...history, ...(serviceError ? [{ role: "assistant" as const, text: "Sorry, I’m having trouble connecting right now. You can still use the guided options below." }] : []), { role: "assistant", text: `${next.interpretation} ${next.explanation}` }]); };
  const ask = async (raw: string) => { const text = raw.trim(); if (!text) return; const history = [...messages, { role: "user" as const, text }]; setMessages(history); setInput(""); setTyping(true); setResult(null); setToolStatus(null); try { const response = await fetch("/api/ai/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text, history: messages, context: { page: window.location.pathname, authenticated: true, propertyAccess: false } }) }); const payload = await response.json() as { mode?: string; reason?: string; message?: string; action?: { label: string; href: string }; toolStatus?: string }; if (response.ok && payload.mode === "ai" && payload.message) { setMessages([...history, { role: "assistant", text: payload.message }]); setResult({ intent: "GENERAL_HELP", interpretation: "", explanation: "", action: payload.action }); setToolStatus(payload.toolStatus ?? null); } else { applyFallback(text, history, payload.reason === "error"); } } catch { applyFallback(text, history, true); } finally { setTyping(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); ask(input); };
  const boughtQuick = () => { setMessages((items) => [...items, { role: "user", text: "I bought a property" }, { role: "assistant", text: "Got it. You bought a property and want to add it to your Property Passport. I’ll guide you through it step by step. Do you have your registered sale deed? You can simply say yes, no, or I’m not sure." }]); setAwaitingSaleDeed(true); setResult(null); };
  return <section className="rounded-[1.75rem] border border-[#dce4da] bg-white p-3 shadow-card sm:p-4"><div className="flex items-center gap-3 rounded-2xl bg-[#f4f8f2] px-4 py-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-moss text-sm font-bold text-white">P</span><div><p className="text-xs font-bold tracking-[.13em] text-moss">PROPERTY PASSPORT ASSISTANT</p><p className="text-xs text-[#6b786f]">A calm guide for every property question</p></div></div><div className="max-h-72 space-y-3 overflow-y-auto px-2 py-4" aria-live="polite">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><p className={`max-w-[90%] rounded-2xl px-4 py-3 text-sm leading-5 ${message.role === "user" ? "bg-moss text-white" : "bg-[#eef4ed] text-ink"}`}>{message.text}</p></div>)}{typing && <div className="flex"><span className="rounded-2xl bg-[#eef4ed] px-4 py-3 text-sm text-[#607067]"><span className="animate-pulse">Thinking</span><span className="ml-1">•••</span></span></div>}</div>{toolStatus && <p className="mx-2 mb-3 rounded-xl bg-[#f7f3e8] px-3 py-2 text-xs font-medium text-[#766033]">{toolStatus}</p>}{result?.action && <div className="border-t border-[#e5ebe4] px-2 pt-3"><Link href={result.action.href} className="block rounded-2xl bg-moss px-5 py-3 text-center text-sm font-semibold text-white">{result.action.label}</Link></div>}<div className="mt-3 flex flex-wrap gap-2 px-1">{prompts.map((prompt) => <button key={prompt} onClick={() => prompt === "I bought a property" ? boughtQuick() : ask(prompt)} className="rounded-full border border-[#c3d0c2] px-3 py-2.5 text-xs font-semibold text-moss hover:bg-[#eef4ed]">{prompt}</button>)}</div><form onSubmit={submit} className="mt-4 flex gap-2 border-t border-[#e5ebe4] pt-4"><input value={input} onChange={(event) => setInput(event.target.value)} className="min-w-0 flex-1 rounded-xl bg-[#f5f8f3] px-4 py-3.5 text-sm outline-none" placeholder="Or tell us in your own words…"/><VoiceButton onTranscript={(text) => { setInput(text); ask(text); }}/><button className="grid h-12 w-12 place-items-center rounded-full bg-moss text-xl text-white" aria-label="Send message">↑</button></form><p className="px-1 pt-3 text-[11px] leading-4 text-[#738076]">You can type or speak. I guide and explain; private records stay protected until you authenticate.</p></section>;
}
