export type NavigatorIntent = "NEW_PROPERTY" | "MY_PROPERTIES" | "APPLICATION_STATUS" | "DOCUMENTS" | "LOST_PASSPORT" | "GENERAL_HELP" | "HUMAN_HELP";

export type NavigationResult = { intent: NavigatorIntent; interpretation: string; explanation: string; action?: { label: string; href: string }; followUp?: "saleDeed" };

// TODO: An authenticated OpenAI/tool-calling adapter can replace this local classifier.
// It must retain this limited intent/result shape and only invoke explicitly allowed services.
export function interpretRequest(input: string, awaitingSaleDeed = false): NavigationResult {
  const text = input.toLowerCase().trim();
  if (awaitingSaleDeed && /^(yes|yeah|yep|i do|i have|have it)\b/.test(text)) return { intent: "NEW_PROPERTY", interpretation: "You have your registered sale deed.", explanation: "Great. I’ll take you through adding your property. We’ll read the useful details from the document, so you don’t need to find any government numbers first.", action: { label: "Start property registration", href: "/register" } };
  if (/person|representative|human|support/.test(text)) return { intent: "HUMAN_HELP", interpretation: "You’d like help from a person.", explanation: "Help request created: PP-HELP-001. An authorised support representative would handle this request." };
  if (/lost|replace.*passport|passport.*missing/.test(text)) return { intent: "LOST_PASSPORT", interpretation: "Your physical Property Passport is lost.", explanation: "Don’t worry. Your property records are not lost with the physical passport. The credential can be revoked and replaced while your Property Passport identity stays the same.", action: { label: "Replace my Passport", href: "/passport/lost" } };
  if (/what.*e-?khata|e-?khata.*(what|mean|is)/.test(text)) return { intent: "GENERAL_HELP", interpretation: "You’re asking what an e-Khata is.", explanation: "An e-Khata is a digital property-record reference used by local authorities. You do not need to understand it to start here; we use plain steps and help collect the right information." };
  if (/document|sale deed|khata|rtc|encumbrance|tax receipt|vault/.test(text)) return { intent: "DOCUMENTS", interpretation: "You want to find a private property document.", explanation: "I can take you to your Property Vault. You’ll need to authenticate before viewing private documents.", action: { label: "Open Property Vault", href: "/scan?next=/passport/property/PROP-001/vault" } };
  if (/application|approved|approval|status|where.*(my|is)/.test(text)) return { intent: "APPLICATION_STATUS", interpretation: "You want to check your property application.", explanation: "I’ll check the latest status of your property application. Your documents have been verified, your property inspection is complete, and it is waiting for final government approval.", action: { label: "View application status", href: "/passport/status" } };
  if (/bought|buy|register|new property|new house|new site|new plot|plot|house/.test(text)) return { intent: "NEW_PROPERTY", interpretation: "You recently bought a property and want to add it to your Property Passport.", explanation: "I’ll take you through property registration. You won’t need to know your PID or Khata number to begin.", action: { label: "Continue", href: "/register" }, followUp: "saleDeed" };
  if (/own|my propert|property number|portfolio/.test(text)) return { intent: "MY_PROPERTIES", interpretation: "You want to see a property you already own.", explanation: "I’ll take you to your private Property Passport, where your verified properties are organised in one place.", action: { label: "View my properties", href: "/passport" } };
  if (/ownership|why.*verif|why.*visit/.test(text)) return { intent: "GENERAL_HELP", interpretation: "You’re asking about the verification process.", explanation: "Verification helps check that the property, documents and applicant details line up. I can explain the general process, but an authorised government officer must make the final determination." };
  return { intent: "GENERAL_HELP", interpretation: "You need guidance with a property question.", explanation: "I can help you understand the general process in plain language. Tell me whether you bought a property, want to check an application, find documents, or need help replacing a passport." };
}
