"use client";

import Link from "next/link";
import { ChangeEvent, DragEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { VoiceButton } from "@/components/voice-button";
import { RegistrationTimeline } from "@/components/registration-timeline";
import { demoExtraction, ExtractedPropertyDetails } from "@/lib/document-extraction-service";

type Stage = "welcome" | "upload" | "reading" | "review" | "timeline" | "verifying" | "issued";
type Details = { owner: string; property: string; area: string; survey: string; registration: string; purchaseDate: string };

const demoDetails: Details = toFormDetails(demoExtraction);
const blankDetails: Details = { owner: "", property: "", area: "", survey: "", registration: "", purchaseDate: "" };
const appointments = ["Monday at 10:00 AM", "Monday at 2:00 PM", "Tuesday at 11:00 AM"];

function Header() { return <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-moss text-lg font-bold text-white">U</span><span className="text-sm font-bold tracking-[.11em] text-ink">UPIS<br/><span className="text-[9px] tracking-[.08em]">PROPERTY IDENTITY</span></span></Link><span className="rounded-full bg-[#e5eee7] px-3 py-1.5 text-xs font-bold tracking-[.12em] text-moss">AI ASSISTANT</span></header>; }

export default function RegistrationPage() {
  const [stage, setStage] = useState<Stage>("welcome");
  const [message, setMessage] = useState("");
  const [details, setDetails] = useState<Details>(blankDetails);
  const [citizenName, setCitizenName] = useState("");
  const [createdPropertyId, setCreatedPropertyId] = useState("");
  const [fileName, setFileName] = useState("");
  const [scheduled, setScheduled] = useState("");
  const [unknownNote, setUnknownNote] = useState(false);
  const [uncertainFields, setUncertainFields] = useState<Array<keyof Details>>([]);
  const [uploadError, setUploadError] = useState("");
  const [verificationStep, setVerificationStep] = useState(3);
  const fileInput = useRef<HTMLInputElement>(null);
  const cameraInput = useRef<HTMLInputElement>(null);
  useEffect(() => { fetch("/api/upis/me").then(async (response) => { if (!response.ok) { window.location.assign("/signin"); return; } const data = await response.json() as { citizen: { name: string } }; setCitizenName(data.citizen.name); setDetails((current) => ({ ...current, owner: data.citizen.name })); }).catch(() => window.location.assign("/signin")); }, []);
  const assistantMessage = useMemo(() => {
    if (stage === "welcome") return "Hi. I can help you add a new property to your Property Passport. Let’s keep this simple — you only need to tell us what you know.";
    if (stage === "upload") return "Great. Upload your registered sale deed and I’ll read the useful details for you.";
    if (stage === "reading") return "Reading your document…";
    if (stage === "review") return "I found these details. Please check them before we continue.";
    if (stage === "verifying") return "Your property verification is in progress. I’ll show you each step as it happens.";
    if (stage === "issued") return "Your Property Passport is ready. Your verified property has been added under your existing Passport.";
    return scheduled ? `You’re all set for the next step. Your property visit is scheduled for ${scheduled}.` : "Your application has been created. The next step is a quick property visit.";
  }, [stage, scheduled]);

  const selectFile = async (file?: File) => { if (!file) return; const accepted = ["application/pdf", "image/jpeg", "image/png"]; if (!accepted.includes(file.type)) { setUploadError("Please choose a PDF, JPG, JPEG or PNG file."); return; } if (file.size > 10 * 1024 * 1024) { setUploadError("This file is larger than 10 MB. Please choose a smaller file."); return; } setUploadError(""); setFileName(file.name); setStage("reading"); const delay = new Promise((resolve) => window.setTimeout(resolve, 1400)); try { const form = new FormData(); form.append("document", file); const response = await fetch("/api/documents/extract", { method: "POST", body: form }); const payload = await response.json() as { details?: ExtractedPropertyDetails; error?: string }; if (!response.ok || !payload.details) throw new Error(payload.error ?? "Could not read this file."); setDetails({ ...toFormDetails(payload.details), owner: citizenName || toFormDetails(payload.details).owner }); setUncertainFields((payload.details.uncertainFields ?? []).map(toFormKey)); } catch { setDetails({ ...demoDetails, owner: citizenName || demoDetails.owner }); setUncertainFields([]); } await delay; setStage("review"); };
  const useDemoSaleDeed = async () => { if (!citizenName) { window.location.assign("/signin"); return; } setUploadError(""); setFileName("Demo Sale Deed (fictional)"); setStage("reading"); await new Promise((resolve) => window.setTimeout(resolve, 1000)); setDetails({ ...demoDetails, owner: citizenName }); setUncertainFields([]); setStage("review"); };
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => selectFile(event.target.files?.[0]);
  const dropFile = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); selectFile(event.dataTransfer.files?.[0]); };
  const submitMessage = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; const text = message.toLowerCase(); setMessage(""); if (text.includes("bought") || text.includes("register") || text.includes("plot") || text.includes("house")) setStage("upload"); };
  const confirm = async () => { try { const response = await fetch("/api/upis/properties", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ address: details.property, area: details.area, surveyNumber: details.survey, registrationNumber: details.registration, purchaseDate: details.purchaseDate }) }); const result = await response.json() as { propertyId?: string; error?: string }; if (!response.ok || !result.propertyId) { setUploadError(result.error ?? "We couldn’t save this property."); return; } setCreatedPropertyId(result.propertyId); setStage("timeline"); } catch { setUploadError("We couldn’t save this property."); } };
  const schedule = async (appointment: string) => {
    if (!createdPropertyId) return;
    setScheduled(appointment); setVerificationStep(3); setStage("verifying");
    const request = fetch(`/api/upis/properties/${createdPropertyId}/verification`, { method: "POST" });
    for (let step = 4; step <= 9; step += 1) { await new Promise((resolve) => window.setTimeout(resolve, 1250)); setVerificationStep(step); }
    const response = await request;
    if (!response.ok) { setUploadError("Verification could not be completed. Please try again."); setStage("timeline"); return; }
    setStage("issued");
  };

  return <main className="min-h-screen bg-cream"><Header /><div className="mx-auto grid max-w-6xl gap-7 px-5 pb-16 sm:px-8 lg:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]">
    <section className="rounded-[2rem] border border-[#dce4dc] bg-white shadow-card">
      <div className="border-b border-[#e4e9e3] px-6 py-5 sm:px-8"><p className="text-xs font-bold tracking-[.16em] text-saffron">YOUR PROPERTY JOURNEY</p><p className="mt-1 text-sm text-[#647168]">Five clear steps. We’ll always explain what happens next.</p><JourneySteps stage={stage}/></div>
      <div className="min-h-[500px] px-5 py-7 sm:px-8"><div className="flex max-w-xl gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-moss text-sm font-bold text-white">P</span><div className="rounded-2xl rounded-tl-sm bg-[#eef4ed] px-4 py-3 text-[15px] leading-6 text-ink">{assistantMessage}</div></div>
        {stage === "welcome" && <div className="ml-12 mt-6 grid max-w-lg gap-3 sm:grid-cols-3"><Choice label="I have my sale deed" onClick={() => setStage("upload")} /><Choice label="I don’t have it" onClick={() => setUnknownNote(true)} /><Choice label="I’m not sure" onClick={() => setUnknownNote(true)} />{unknownNote && <p className="sm:col-span-3 rounded-xl bg-[#fff5e9] p-4 text-sm leading-5 text-[#7b542c]">That’s okay. We can verify it during the property check. Start with anything you have, or tell us more below.</p>}</div>}
        {stage === "upload" && <div className="ml-0 mt-7 max-w-xl"><div onDrop={dropFile} onDragOver={(event) => event.preventDefault()} className="rounded-3xl border-2 border-dashed border-[#aac1ae] bg-[#f5f8f3] p-8 text-center sm:p-11"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white text-2xl text-moss shadow-sm">↑</span><h2 className="mt-4 text-xl font-semibold">Upload your registered sale deed</h2><p className="mt-2 text-sm leading-5 text-[#647168]">Drop a PDF, JPG, JPEG or PNG here (up to 10 MB). Your document is used only to help you review the property details.</p><input ref={fileInput} type="file" accept="application/pdf,image/jpeg,image/png" className="sr-only" onChange={handleFile} /><input ref={cameraInput} type="file" accept="image/jpeg,image/png" capture="environment" className="sr-only" onChange={handleFile} /><button onClick={() => fileInput.current?.click()} className="mt-6 rounded-full bg-moss px-5 py-3 text-sm font-semibold text-white hover:bg-[#244738]">Choose file</button><button className="ml-2 mt-3 rounded-full border border-[#b9c8ba] px-5 py-3 text-sm font-semibold text-moss" onClick={() => cameraInput.current?.click()}>Take a photo</button><button onClick={useDemoSaleDeed} className="mt-3 block w-full rounded-full border border-[#d2b56c] bg-[#fff9eb] px-5 py-3 text-sm font-semibold text-[#775522]">Use sample sale deed</button><p className="mt-3 text-xs leading-5 text-[#718076]">Use the fictional sample document to explore the competition prototype without uploading a file.</p>{uploadError && <p className="mt-4 rounded-xl bg-[#fff5e9] p-3 text-sm text-[#7b542c]">{uploadError}</p>}</div></div>}
        {stage === "reading" && <div className="ml-12 mt-8 max-w-lg rounded-3xl border border-[#e1e8e0] p-7"><p className="text-xs font-bold tracking-[.14em] text-saffron">READING YOUR DOCUMENT</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e5ece4]"><span className="block h-full w-2/3 animate-pulse rounded-full bg-saffron" /></div><p className="mt-5 font-semibold">{fileName || "Sale deed"}</p><p className="mt-1 text-sm text-[#647168]">Finding the important details for you…</p></div>}
        {stage === "review" && <div className="mt-7"><div className="mb-4 ml-12"><p className="text-xs font-bold tracking-[.14em] text-saffron">I FOUND THESE DETAILS</p><p className="mt-1 text-xs font-bold tracking-[.12em] text-[#737f76]">EXTRACTED FROM YOUR DOCUMENT</p></div><div className="grid gap-3 sm:grid-cols-2">{([ ["Owner", "owner"], ["Property", "property"], ["Area", "area"], ["Survey number", "survey"], ["Registration number", "registration"], ["Purchase date", "purchaseDate"] ] as const).map(([label, key]) => <label key={key} className="rounded-2xl border border-[#dbe4da] p-4"><span className="block text-xs font-bold tracking-[.08em] text-[#7a887e]">{label.toUpperCase()}</span><input value={details[key]} onChange={(event) => { setDetails({ ...details, [key]: event.target.value }); setUncertainFields((fields) => fields.filter((field) => field !== key)); }} className="mt-2 w-full bg-transparent font-medium text-ink outline-none" />{uncertainFields.includes(key) && <span className="mt-2 block text-xs text-[#9b6326]">We couldn’t confidently read this field. Please enter it manually.</span>}</label>)}</div><p className="mt-5 text-sm text-[#647168]">Please check these details before continuing.</p><button onClick={() => setUnknownNote(true)} className="mt-4 text-sm font-semibold text-moss underline underline-offset-4">I don’t know one of these details</button>{unknownNote && <p className="mt-3 rounded-xl bg-[#fff5e9] p-4 text-sm text-[#7b542c]">That’s okay. We can verify that during the property check.</p>}<p className="mt-5 rounded-xl bg-[#f5f8f3] p-3 text-sm text-[#526158]">You are confirming that these details are correct.</p><button onClick={confirm} className="mt-4 w-full rounded-2xl bg-moss px-5 py-4 font-semibold text-white hover:bg-[#244738]">Everything looks correct</button></div>}
        {stage === "timeline" && <div className="mt-7"><div className="rounded-2xl bg-[#eef4ed] p-5"><p className="text-xs font-bold tracking-[.14em] text-moss">APPLICATION CREATED</p><p className="mt-2 text-lg font-semibold">Your application has been created.</p></div><RegistrationTimeline scheduled={Boolean(scheduled)} /><div className="mt-5 rounded-3xl border border-[#dce4dc] bg-white p-5"><p className="text-xs font-bold tracking-[.14em] text-saffron">WHAT HAPPENS NEXT?</p><p className="mt-2 font-semibold">Choose a time for your property visit.</p><p className="mt-1 text-sm leading-5 text-[#647168]">After the visit, UPIS completes each verification stage for this competition prototype.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{appointments.map((appointment) => <button key={appointment} onClick={() => schedule(appointment)} className="rounded-2xl border border-[#bfd0bf] px-3 py-4 text-sm font-semibold text-moss hover:border-moss hover:bg-[#eef4ed]">{appointment.replace(" at ", "\n")}</button>)}</div><a href="/#assistant" className="mt-5 inline-block text-sm font-semibold text-moss underline">Need help?</a></div></div>}
        {stage === "verifying" && <div className="mt-7 space-y-5"><div className="rounded-[1.75rem] border border-[#dce4dc] bg-white p-6 shadow-card"><p className="text-xs font-bold tracking-[.16em] text-saffron">CURRENT STEP</p><h2 className="mt-2 text-2xl font-semibold">{["Property visit scheduled", "Officer verification", "Internal verification", "Government verification", "Ownership confirmation", "Property Passport creation", "Passport ready"][Math.max(0, verificationStep - 3)]}</h2><p className="mt-5 text-xs font-bold tracking-[.14em] text-[#77857a]">WHAT&apos;S HAPPENING</p><p className="mt-2 text-sm leading-6 text-[#647168]">{verificationStep < 5 ? "An authorised officer is verifying the property details." : verificationStep < 8 ? "Your verification record is being reviewed and prepared for approval." : "Your verified property is being linked to your Property Passport."}</p></div><RegistrationTimeline scheduled approved={false} currentStep={verificationStep} /></div>}
        {stage === "issued" && <div className="mt-7 rounded-[1.75rem] bg-[#183e31] p-7 text-white shadow-card"><p className="text-xs font-bold tracking-[.16em] text-[#d5e5d1]">PROPERTY VERIFIED</p><h2 className="mt-2 text-3xl font-semibold">Your property has been added to the UPIS records.</h2><p className="mt-6 text-xs font-bold tracking-[.16em] text-[#d5e5d1]">PROPERTY PASSPORT READY</p><p className="mt-2 text-sm leading-6 text-[#d5e5d1]">Your verified property is now linked to your Property Passport.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/passport?download=1" className="inline-flex rounded-2xl bg-[#e5c97d] px-5 py-3 font-semibold text-[#183e31]">Download Property Passport</Link><Link href="/passport" className="inline-flex rounded-2xl border border-white/35 px-5 py-3 font-semibold text-white">View my Property Passport</Link></div></div>}
      </div>
      <form onSubmit={submitMessage} className="flex items-center gap-2 border-t border-[#e4e9e3] p-4 sm:p-5"><input value={message} onChange={(event) => setMessage(event.target.value)} className="min-w-0 flex-1 rounded-xl bg-[#f5f8f3] px-4 py-3 text-sm outline-none" placeholder="Tell me what you need…" /><VoiceButton onTranscript={setMessage} /><button className="grid h-11 w-11 place-items-center rounded-full bg-moss text-xl text-white" aria-label="Send message">↑</button></form>
    </section>
    <aside className="lg:pt-16"><div className="rounded-[1.75rem] bg-[#315e4c] p-7 text-white"><p className="text-xs font-bold tracking-[.15em] text-[#d7e4d5]">DESIGNED FOR CLARITY</p><h2 className="mt-3 text-2xl font-semibold leading-tight">You never need to hunt through property jargon.</h2><p className="mt-4 text-sm leading-6 text-[#d7e4d5]">We ask for what you know, use documents where possible, and explain what happens next.</p></div><p className="mt-5 px-2 text-xs leading-5 text-[#718077]">This is a fictional competition prototype. It does not connect to government records or retain real documents.</p></aside>
  </div></main>;
}

function Choice({ label, onClick }: { label: string; onClick: () => void }) { return <button onClick={onClick} className="rounded-2xl border border-[#bfd0bf] bg-white px-4 py-4 text-left text-sm font-semibold text-moss transition hover:border-moss hover:bg-[#eef4ed]">{label}</button>; }
function JourneySteps({ stage }: { stage: Stage }) { const current = stage === "welcome" || stage === "upload" || stage === "reading" || stage === "review" ? 0 : 2; const steps = ["Tell us about your property", "Verify your documents", "Meet us at your property", "Government approval", "Property Passport"]; return <ol className="mt-5 grid grid-cols-5 gap-2">{steps.map((step, index) => <li key={step} className="min-w-0"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index < current ? "bg-moss text-white" : index === current ? "bg-saffron text-white" : "bg-[#e5ebe4] text-[#718076]"}`}>{String(index + 1).padStart(2, "0")}</span><span className={`mt-2 block text-[10px] leading-3 ${index === current ? "font-bold text-ink" : "text-[#718076]"}`}>{step}</span></li>)}</ol>; }
function toFormDetails(details: ExtractedPropertyDetails): Details { return { owner: details.ownerName, property: details.propertyAddress, area: details.area, survey: details.surveyNumber, registration: details.registrationNumber, purchaseDate: details.purchaseDate }; }
function toFormKey(field: keyof Omit<ExtractedPropertyDetails, "uncertainFields">): keyof Details { return ({ ownerName: "owner", propertyAddress: "property", area: "area", surveyNumber: "survey", registrationNumber: "registration", purchaseDate: "purchaseDate" } as const)[field]; }
